// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class StandardizeCustomerPhoneNumber9Digits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StandardizeCustomerPhoneNumber9Digits));
        
        string IMigrationMetadata.Id
        {
            get { return "202608311332315_StandardizeCustomerPhoneNumber9Digits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
