// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class StandardizeCustomerPhoneNumber1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StandardizeCustomerPhoneNumber1));
        
        string IMigrationMetadata.Id
        {
            get { return "202608311326006_StandardizeCustomerPhoneNumber1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
