// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class CheckModelSync : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckModelSync));
        
        string IMigrationMetadata.Id
        {
            get { return "202610032004108_CheckModelSync"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
