// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SyncTermsAcceptanceSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncTermsAcceptanceSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "202610032100554_SyncTermsAcceptanceSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
